name: Vivaciousness
favicon: null
layout_spectrum: 0.6073886319063604
typography_spectrum: 0.8063367679715157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3370138253085315
  lightness: 0.32843657792545855
  saturation: 0.4985720971599221
  rhythmicContrast: 0.38213634374551475
purpose: []
